[package]
name = "acm"
version = "0.1.0"
edition = "2018"

[workspace]
members = ["server", "ramiel"]

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1"
