FROM rustlang/rust:nightly AS builder
COPY . .
RUN cargo build --release --package server

FROM debian:bullseye-slim AS runtime

RUN apt-get update; \
    apt-get install -y openssl ca-certificates; \
    rm -rf /var/lib/apt/lists/*

COPY --from=builder /target/release/server /usr/local/bin/server

CMD ["server"]
