[package]
edition = "2021"
name = "app"
version = "0.1.0"

[dependencies]
log = "0.4"
markdown = "0.3"
monaco = { git = "https://github.com/siku2/rust-monaco", features = ["yew-components"] }
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
wasm-logger = "0.2"
wee_alloc = "0.4"
yew = "0.19"
yew-router = "0.16"
