[build]
dist = "../dist/"

[watch]
watch = [
    "tailwind.config.js",
    "./index.html",
    "src/"
]

[[hooks]]
stage = "pre_build"
command = "tailwindcss"
command_arguments = ["-o", "styles.css", "--minify"]
